apiVersion: v1
kind: Pod
metadata:
  name: okd-in-use-pod-example
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
      - containerPort: 80
        targetPort: 8080
