apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: okd-in-use-replicaset
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: frontend-app
          image: nginxinc/nginx-unprivileged:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 20m
              ephemeral-storage: 30Mi
              memory: 25Mi
            requests:
              cpu: 6m
              ephemeral-storage: 10Mi
              memory: 25Mi
